[versions]
android = "8.0.2"
fragment-ktx = "1.5.7"
kotlin = "1.8.0"
androidx-core = "1.10.1"
androidx-core-splashscreen = "1.0.1"
androidx-appcompat = "1.6.1"
androidx-fragment = "1.6.0"
androidx-lifecycle = "2.6.1"
androidx-preference = "1.2.0"
kotlinx-coroutines-core = "1.4.3"
material = "1.9.0"
tablericons = "0.9.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
tablericons = { group = "ir.alirezaivaz", name = "tablericons", version.ref = "tablericons" }

[plugins]
application = { id = "com.android.application", version.ref = "android" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]
